apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-mongo-pacman-ywry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-mongo-pacman-ywry
    app.kubernetes.io/part-of: my-app
  name: mongo-mongo-pacman-ywry
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongo-mongo-pacman-ywry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongo-mongo-pacman-ywry
    spec:
      containers:
      - image: quay.io/jduimovich0/user-workload@sha256:65ec5f9073fb4e661a0e959ab18c05d2ad8e40c2664e9626583a74630bb40199
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
