apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongo-mongo-pacman-ywry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongo-mongo-pacman-ywry
    app.kubernetes.io/part-of: my-app
  name: mongo-mongo-pacman-ywry
  namespace: user1-tenant
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/instance: mongo-mongo-pacman-ywry
status:
  loadBalancer: {}
