apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo-mongo-pacman-ywry
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/user-workload@sha256:65ec5f9073fb4e661a0e959ab18c05d2ad8e40c2664e9626583a74630bb40199
        name: container-image
        resources: {}
status: {}
